---
title: "Module 7 Programming Assignment"
author: "Tuan Nguyen"
date: "6/25/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r IMPORT DATASET}
### This dataset comes from a chemical analysis of wines grown in Italy but derived from three different cultivars. I will use unsupervised machine learning (K-Means Clustering) to identify which of the three cultivars each data instance would be clusted in.

### The dataset can be found at the UCI Machine Learning Repository or at this link: https://archive.ics.uci.edu/ml/datasets/Wine

rm(list=ls())
df <- read.csv(file = 'C:\\Users\\cg\\Desktop\\Echo\\School\\DSC607\\Week 7\\wine.csv')
```

```{r BASIC INFO}
### Generate basic information about the dataset with some standard R functions

head(df)
nrow(df)
ncol(df)
str(df)
summary(df)
```

```{r Preprocessing}
### K-Means is a type of unsupervised machine learning so we do not need the "Class" attribute in our data. A new data frame called "data" is created without this "Class" atribute.

data <- df
data$Class <- NULL
data
```


``` {R K Means}
### K-means is a technique used in Cluster Analysis to divide data into clusters that are meaningful or useful. The goal of K-means and cluster analysis, in general, is to group data objects in clusters so the objects within a cluster are similar to each other while different from objects in other clusters. In R, we would use the kmeans() command, with two arguments. The first argument is the name of our data frame, and the second argument is the number of clusters we would like to cluster our data into. Since our original dataset contained three different classes, we will cluster our data into three different clusters

kmeans <- kmeans(data, 3)
kmeans
```

```{r Comparisons}
### The above kmeans() command was able to cluster our data into 3 clusters of size {47, 69, 62}. We'll compare this to our original dataset with a table(). 

table <- table(df$Class, kmeans$cluster)
table
```

``` {R Table}
### The result of the table shows there are 59 instances of Class 1 in the original dataset, with our clustering algorithm grouping 46 instances in Cluster 1 and 13 instances in Cluster 2.

### There are 71 instances of Class 2 in the original dataset, and our clustering algorithm grouped 1 instance in Cluster 1, 50 instances in clsuter 2, and 20 instances in cluster 3.

### Lastly, there are 48 instances of Class 3 in the original dataset, with our clustering algorithm grouping 19 instances in Cluster 2 and 29 instances in Cluster 3.
```